# Generated by Django 6.0.2 on 2026-03-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickNotesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
