# Generated by Django 6.0.2 on 2026-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickNotesApp', '0002_remove_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
