# Generated by Django 6.0.2 on 2026-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickNotesApp', '0003_note_color_note_reminder_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('white', '⚪ Default'), ('red', '🔴 Urgent'), ('yellow', '🟡 Important'), ('green', '🟢 Done'), ('blue', '🔵 Idea'), ('purple', '🟣 Personal')], default='white', max_length=20),
        ),
    ]
